### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [astronomer/airflow-chart#147]
The markup version of the readme that is displayed for the main page in this repo contains the following link:
Status code [404:NotFound] - Link: https://github.com/astronomer/astronomer/tree/master/docker/airflow
(The link in the readme’s raw markdown may appear in a different format to the link above

This bad link was found by a tool I very recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
I (a human) verified that this link is broken and have manually logged this Issue (i.e. this Issue has not been created by a bot).
If this has been in any way helpful then please consider giving the above Repo a Star.
If you have any feedback on the information provided here, or on the tool itself, then please feel free to share your thoughts and pass on the feedback.

**Comment by danielhoherd** [comment]
@MrCull Thanks for the submission. We have recently begun using [muffet](https://github.com/raviqqe/muffet) a bit, though not for checking README.md files in git. If that doesn't work for our needs we'll check out your project.
