### ISSUE TITLE
Error: column serialized_dag.dag_hash does not exist

### ISSUE THREAD

**Issue by saikatharryc** [astronomer/airflow-chart#170]
I'm using : https://github.com/astronomer/ap-airflow/tree/master/1.10.12

Seems like one more column it needs to create?

<img width="499" alt="Screen Shot 2020-12-06 at 12 10 40 AM" src="https://user-images.githubusercontent.com/15653282/101260696-82bc6800-3757-11eb-96ec-03e15e04083f.png">

Logs from my scheduler:

<img width="899" alt="Screen Shot 2020-12-05 at 11 45 05 PM" src="https://user-images.githubusercontent.com/15653282/101260238-839fca80-3754-11eb-88b6-ca86f06fff94.png">

**Comment by saikatharryc** [comment]
When it runs from the mmigration job, it does not populate some of the fields, If I execute into the scheduler, and do an `airflow upgradedb` it populates the changes, and the scheduler works.
anyone is aware of this issue?

**Comment by saikatharryc** [comment]
Got it,
This happened due to https://github.com/astronomer/airflow-chart/blob/master/templates/run-airflow-migrations.yaml#L60 I did not change, and if do not, then it takes this value:  https://github.com/astronomer/airflow-chart/blob/master/values.yaml#L68. In which case, `dag_hash` does not exist probably.
if I change the default version from `1.10.10-buster` to `1.10.12-buster`, it worked.

**Comment by dinigo** [comment]
What was the solution for this issue? I'm experiencing this with airflow image on docker-compose. Should a migration be created to populate this column in the db?

**Comment by saikatharryc** [comment]
> What was the solution for this issue? I'm experiencing this with airflow image on docker-compose. Should migration be created to populate this column in the db?

Short Answer: Yes

replace this:  https://github.com/astronomer/airflow-chart/blob/master/values.yaml#L89
with this: `{{ template "airflow_image" . }}`

the image core version used to run the migration is different (older) in my case, than the one that I'm using for the workers and scheduler. in here: https://github.com/astronomer/airflow-chart/blob/master/values.yaml#L87
