### ISSUE TITLE
Webserver with 2 or more replicas gives CSRF error

### ISSUE THREAD

**Issue by saikatharryc** [astronomer/airflow-chart#171]
When I set webserver replicas to 2 or more. it gives a CSRF error.
any idea on this?
with the same, if I set replicas 1, it does work as it supposes to be.

**Comment by kaxil** [comment]
Set this config option https://airflow.apache.org/docs/apache-airflow/2.0.1/configurations-ref.html#secret-key

Without it, each machine will get it's own secret key, and won't accept CSRF tokens from the other machine(s)

**Comment by kaxil** [comment]
Let us know if it does not work with it, we can reopen the issue if that's the case
