### ISSUE TITLE
Astronomer maintenance of this repo?

### ISSUE THREAD

**Issue by blake-enyart** [astronomer/airflow-chart#189]
Hello,

I noticed that several issues have been outstanding in this repo for several months. I was looking to adopt this helm chart. Are you all still maintaining this?

Otherwise, is there an alternative you can recommend to get started with?

**Comment by patchandpray** [comment]
From what I have read the aim is that this repo will eventually be archived and the helm chart in the official apache/airflow repository should be used. For now there are still some issues open there with regards to airflow 2.0 which have made me use this chart. 

So if you are looking to use Airflow 2.0 with HELM your best bet for now is this chart.

Maybe it is a good idea to update the readme in this repository to point out that this chart will no longer be maintained in the future and the upstream chart should be used?

**Comment by blake-enyart** [comment]
> From what I have read the aim is that this repo will eventually be archived and the helm chart in the official apache/airflow repository should be used. For now there are still some issues open there with regards to airflow 2.0 which have made me use this chart. 
> 
> 
> 
> So if you are looking to use Airflow 2.0 with HELM your best bet for now is this chart.
> 
> 
> 
> Maybe it is a good idea to update the readme in this repository to point out that this chart will no longer be maintained in the future and the upstream chart should be used?

Yeah, that's my thought to. This feels like abandonware at this point.

**Comment by kaxil** [comment]
Hi folks, @patchandpray @blake-enyart -- Yes this chart is very much maintained and is used by 200+ deployments in Astronomer Cloud and tons of Enterprise customers. 

This chart was the basis of the chart at apache/airflow. For some reason we didn't got notified of issues creation on this repo .
