### ISSUE TITLE
Can not change webserver.defaultUser.password when install by helm

### ISSUE THREAD

**Issue by patsevanton** [astronomer/airflow-chart#196]
Hello! Thanks for helm chart for airflow

I try install helm chart or airflow from astronomer
```
helm repo add astronomer https://helm.astronomer.io
helm repo update
helm install --set webserver.defaultUser.password=new_password,airflowVersion=2.0.0,defaultAirflowTag=2.0.0-buster,ingress.enabled=true,ingress.baseDomain=192.168.22.7.sslip.io airflow astronomer/airflow
```

I login to airflow as admin:admin.
But i think login as admin:new_password

**Comment by kaxil** [comment]
Similar to https://github.com/apache/airflow/issues/14872 -- we were not able to reproduce this. Please let us know if this is still an issue
