### ISSUE TITLE
Using Google Cloud Storage remote logging

### ISSUE THREAD

**Issue by PoulpiFr** [astronomer/airflow-chart#213]
Hello 🧑‍🚀  folks,

While using this chart, I'm trying to configure Google Cloud Storage remote logging: https://airflow.apache.org/docs/apache-airflow-providers-google/stable/logging/gcs.html

As per the documentation says, I need to:
a. Tweak the Airflow config to pass the proper params (Service Account PATH, GCS bucket name, ...)
b. Write the JSON credentials Key of a Google Service Account alongside Airflow (e.g. in the Airflow Pods).

To configure Airflow (a.), it's quite simple, I use the Airflow config env variables (`AIRFLOW__LOGGING__XXXX`) that I inject in this Chart through the `.Values.env` value. 👍

However, I don't see any way of writing the Google Service Account credentials JSON file into the Airflow Pods. I currently have the credentials file stored into a Kubernetes secret and I would like to inject it as a file into Airflow Pods.

Things that I tried but didn't work:
1/ I found ways to bind Kubernetes Secrets to env variables with this Chart (`.Values.secrets[]`) but I need a file, not an Env variable (Google auth libs wants to have the credentials into Files, not Env vars, see: https://cloud.google.com/docs/authentication/production#automatically).
2/ I saw that there was a way to mount files into the worker and scheduler (`.Values.workers.extraVolumeMounts` / `.Values.workers.extraVolumes` / `.Values.scheduler.extraVolumeMounts` / `.Values.scheduler.extraVolumes`) but I don't see it possible for the `webserver` and as I want the Airflow UI to fetch the logs from GCS when reading a task log, I guess that it won't work (Airflow would write the logs but wouldn't be able to read them)

Did I miss anything?

If needed I can open a PR to propose a way to mount any volume, such as `.Values.extraVolumeMounts` / `.Values.extraVolumes`.

**Comment by kaxil** [comment]
https://github.com/astronomer/airflow-chart/pull/214 should address this
