### ISSUE TITLE
airflow command error: argument GROUP_OR_COMMAND: invalid choice: 'serve_logs'

### ISSUE THREAD

**Issue by nicks** [astronomer/airflow-chart#236]
Hi! I'm trying to upgrade to Airflow 2.0 with this chart. When I upgrade, I get an error:

```
airflow command error: argument GROUP_OR_COMMAND: invalid choice: 'serve_logs'
```

Here is where `serve_logs` is getting invoked:

https://github.com/astronomer/airflow-chart/blob/df9dfaf4179fc942f4bdc98b0c9ae33bfc625d04/templates/scheduler/scheduler-deployment.yaml#L157

But AFAICT, this command does not exist in Airflow 2.0.

Am I missing something? Or is this chart not compatible with Airflow 2.0?

Thanks!

**Comment by kaxil** [comment]
It's a bug, use Celery ot Kubernetes Executor, it should work fine with that with Airflow 2.x

cc @jedcunningham

**Comment by jedcunningham** [comment]
Just a word of caution, moving to `KubernetesExecutor` alone won't "fix" this. It'll run but you wont have any task logs. You'd want to set up remote logging if you choose to go that route.

#237 will fix this.
