### ISSUE TITLE
Unable to install chart "Deployment is not ready: airflow/airflow-scheduler"

### ISSUE THREAD

**Issue by flyerhawk** [astronomer/airflow-chart#286]
When I run "helm install airflow -n airflow astronomer/airflow" it fails saying waiting on condition.  

When I run "helm install airflow -n airflow astronomer/airflow --debug --wait" I get the above error.  

Any idea how to troubleshoot this?

**Comment by jedcunningham** [comment]
Neither this chart, nor the OSS chart subchart it uses, supports using the `--wait` flag. See https://github.com/apache/airflow/issues/11979.
