### ISSUE TITLE
Expose serviceAccounts to attach to webserver and scheduler as variable

### ISSUE THREAD

**Issue by snithish** [astronomer/airflow-chart#76]
We have a specific requirement where in airflow DAG reads a file from S3 to determine how to tasks to instantiate, so trying to access S3 using RBAC, possibility to attach custom service accounts would make this easier.

**Comment by schnie** [comment]
Hey @snithish, we actually have an internal issue right now to add support for this. We'll be adding default service accounts to the rest of the Airflow pods and adding a new option like `serviceAccountAnnotations`, where we can pass arbitrary annotations through (specifically for this issue).

These will flow through to any pods that parse the dag files or execute tasks.

Would that work for use-case?

**Comment by snithish** [comment]
@schnie yes if annotations could be added to a default service accounts that would be the best. From your response, I infe that even Kubernetes  Worker Pods when running with KubernetesExecutor would also have this same default service account, I am right?

Plus is there a ETA on this?

**Comment by schnie** [comment]
Hey @snithish this should be available as part of our 0.14 release, either later this week or next week. The KubernetesExecutor pods should work out of the box but KubernetesPodOperator pods may need to be manually specified to attach to that specific service account.

**Comment by snithish** [comment]
@schnie Thanks for the update :+1: 
I will keep an eye out for 0.14 version, closing this issue then.
