### ISSUE TITLE
Sharing steps for prototyping installation on Docker-for-Mac + Kubernetes

### ISSUE THREAD

**Issue by lewismc** [astronomer/airflow-chart#89]
Hi Folks,

We've been evaluating Apache Airflow and are going ahead with it :)
I recently came across @schnie post on [dev@airflow](https://lists.apache.org/thread.html/r55b09d63a809428c20ca3317801cad5a86ac939478e0dbd8e93f0fee%40%3Cdev.airflow.apache.org%3E) so started looking at this repository. You guys have done an EXCELLENT job! kudos.

In parallel with having our SRE prototype installation into our test env, I wanted our developers to be able to write, deploy and test their own DAG's even before they interact with the test env. The following therefore documents what I had to do to get this working. 

**Install astronomer/airflow helm chart on docker-deskop (Kubernetes)**
```
brew install helm
kubectl create namespace airflow
helm repo add astronomer https://helm.astronomer.io
helm repo update
helm install airflow astronomer/airflow
kubectl get pods --all-namespaces
helm list -n airflow
kubectl port-forward svc/airflow-webserver 8080:8080 -n airflow
# access Airflow dashboard via localhost:8080
```

**Deploy container DAG's into Airflow**
```
brew install astronomer/tap/astro
mkdir sample-airflow-project && cd sample-airflow-project
astro dev init
docker build -t sample-airflow-dag:0.0.1 .
helm upgrade airflow -n airflow --set images.airflow.repository=sample-airflow-dag --set images.airflow.tag=0.0.1 astronomer/airflow
kubectl port-forward svc/airflow-webserver 8080:8080
#access Airflow dashboard via localhost:8080
```

I'm not sure what you guys want to do with this info... maybe a wiki entry?

**Comment by danielhoherd** [comment]
Honestly, the best way to get devs up and running quickly with writing and running dags is to use `astro dev`. <https://docs.astronomer.io/astro/cli/overview>
